// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'zotero-arxiv-daily-menu-open'
  | 'zotero-arxiv-daily-name'
  | 'zotero-arxiv-daily-profile-exclude'
  | 'zotero-arxiv-daily-profile-include'
  | 'zotero-arxiv-daily-profile-menu';
