// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "setupComplete": boolean;
      "recommendationCount": number;
      "embeddingProvider": string;
      "embeddingBaseURL": string;
      "embeddingAPIKey": string;
      "embeddingModel": string;
      "embeddingDimensions": number;
      "embeddingBatchSize": number;
      "allowInsecureLocalhost": boolean;
      "llmEnabled": boolean;
      "llmProvider": string;
      "llmBaseURL": string;
      "llmAPIKey": string;
      "llmModel": string;
      "networkTimeoutMs": number;
      "arxivCategories": string;
    };
  }
}
